### ISSUE TITLE
Gamma-Psi-Sleights raise infection rating to 100 when used.

### ISSUE THREAD

**Issue by IsThisMyRealName** [Artemystra/eclipsephase#77]
First off: Thank you for your amazing work! My group is new to EP and we really enjoy the system you build!
That said there seems to be a problem with Gamma-Sleights. When they are used the infection rating goes to 100 instantly.
These are the sleights I tested:
![image](https://github.com/Artemystra/eclipsephase/assets/18038861/c18049a7-3848-4702-bf67-6b47447a9a9e)
All of them have this problem.
It might be that the calculation is missing a "+" because at least the message in chat displays "infection rating raised to 4010" when it should say "infection rating raised to 40+10" or "50"
![image](https://github.com/Artemystra/eclipsephase/assets/18038861/f9bdd60b-9fc7-4545-b0c6-f8fea103d2e7)

(Also there is a typo in the Motivation "Foil Plans" for "The Stranger" strain. It is written as "Foll Plans")
![image](https://github.com/Artemystra/eclipsephase/assets/18038861/5a27f591-f776-4081-bf65-d9f005e47be1)

**Comment by Artemystra** [comment]
Hey there,

Thank you for posting this. While I know this error, I believe, that it is due to a field attribution error from my side, that I failed to correct during the last update.

What you can try is just putting in any value above 20 to change it from being a string to being a number.

I‘ll also have a look into it during my future work, but currently struggling a bit with the new selection-fields which will slow the next update a bit.

**Comment by Artemystra** [comment]
This issue has been fixed and released in v1.1.3 of the current system
